version: '2'
services:
  margintradingpublic:
    image: lykkex/margintradingpublic
    container_name: margintradingpublic
    environment:
      - SettingsUrl=${SettingsUrl}
      - IsLive=${IsLive}
      - Env=${Env}
      - KestrelThreadCount=${KestrelThreadCount}
    ports:
      - "5010:5010"
    networks:
      mynet:
        aliases:
          - margintradingpublic

networks:
  mynet:
    driver: bridge
