version: '2'
services:
  margintrading:
    image: lykkedev/margintradingdatareader:dev
    container_name: margintradingdatareader
    environment:
      - SettingsUrl=${SettingsUrl}
      - IsLive=${IsLive}
    ports:
      - "5000:5000"
    networks:
      mynet:
        aliases:
          - margintradingdatareader
networks:
  mynet:
    driver: bridge
