version: '2'
services:
  margintradingfront:
    image: lykkex/margintradingfront
    container_name: margintradingfront
    environment:
      - SettingsUrl=${SettingsUrl}
      - IsLive=${IsLive}
      - Env=${Env}
      - KestrelThreadCount=${KestrelThreadCount}
    ports:
      - "5005:5005"
    networks:
      mynet:
        aliases:
          - margintradingfront

networks:
  mynet:
    driver: bridge
